# Generated by Django 4.1.3 on 2022-11-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
