# Generated by Django 4.1.3 on 2022-11-11 19:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_value_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='id',
        ),
        migrations.AddField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
