# Generated by Django 4.1.3 on 2022-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_value_id_value_created_at_alter_value_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
